site_name: General Template Site
site_url: https://nameofwebsite.com

nav:
    
    - Aboutme: 'aboutme.md'
    - Index: 'index.md'
    - Page 1: 
        - page1: 
            - 'page/page1.md'
        - subpage: 
            - 'page/subpage.md'
            - 'page/subsubpage.md'
        - subsubpage:
            - subsubsubpage:
                - 'page/subsubsubpage.md'
    - Page 2: 
        - page1: 
            - 'page/page1.md'
        - subpage: 
            - 'page/subpage.md'
            - 'page/subsubpage.md'
        - subsubpage:
            - subsubsubpage:
                - 'page/subsubsubpage.md'
    - Page 3: 
        - page1: 
            - 'page/page1.md'
        - subpage: 
            - 'page/subpage.md'
            - 'page/subsubpage.md'
        - subsubpage:
            - subsubsubpage:
                - 'page/subsubsubpage.md'
    - testpage: 'aboutme.md'
theme: material
  